# Generated by Django 4.1 on 2024-01-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='health',
        ),
    ]
