# Generated by Django 4.1 on 2024-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_rename_todo_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
